
variables:
  REGISTRY: registry.gitlab.com
# cache:
#   untracked: true
#   key: "$CI_BUILD_REF_NAME"
#   paths:
#     - node_modules/
stages:
  - build
  - build_docker
  # - deploy
build_site:
  stage: build
  image: node:8.9.3-alpine
  before_script:
  - apk add --no-cache automake nasm autoconf build-base zlib zlib-dev freetype libpng libjpeg-turbo freetype-dev libpng-dev libjpeg-turbo-dev  libwebp libwebp-dev
  # - apk --update --no-cache add nodejs nodejs-npm automake git alpine-sdk nasm autoconf build-base zlib zlib-dev freetype libpng libjpeg-turbo freetype-dev libpng-dev libjpeg-turbo-dev  libwebp libwebp-dev
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    # untracked: true
    paths:
      - dist/
build_docker:
  stage: build_docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/tuanzhang/store .
    - docker push registry.gitlab.com/tuanzhang/store:latest
  only:
    - master
# deploy:
#   image: stackahoy/stackahoy-cli
#   stage: deploy
#   script:
#     - stackahoy deploy -t $STACKAHOY_TOKEN -b production -r $REPO_ID --skip-delivery
#   only:
#     - production
#   tags:
#     - docker

# gitlab-runner exec docker build_site --docker-privileged